### ISSUE TITLE
Implement "reconnect" command

### ISSUE THREAD

**Issue by kzidane** [cmorisse/ikp3db#6]
It appears that there are at least a couple of commands that are missing from `ikp3db` that are invoked by the debugger implementation plugin on Cloud9's end, namely [`reconnect`](https://github.com/c9/core/blob/15911b3ed65e69efd27d19683a2ac90c69ca4242/plugins/c9.ide.run.debug.ikpdb/ikpdb.js#L485) which is executed after reload and in other implementations seems to suspend if the program is running or just return the `stopped` execution state otherwise, and [`getStatus`](https://github.com/c9/core/blob/15911b3ed65e69efd27d19683a2ac90c69ca4242/plugins/c9.ide.run.debug.ikpdb/ikpdb.js#L427) executed after `reconnect` to fetch information about the stack frame.

I've been trying to familiarize myself with the code and was able to implement both of them but just wanted to confer first before opening a new PR since neither execution state nor last frame (or frames dump for that matter) seem to be remembered anywhere? What would be the best way to go about this? Just adding a couple of instance variables to the `IKPdb` class to remember these pieces of data and using them in the implementation of these commands?

Thank you!

**Comment by cmorisse** [comment]
I'm currently working on this one.
I think it's a little bit more complicated. Currently, I'm trying to:
* move socket.accept() into IKPdbConnectionHandler()
* ensure that some commands are dropped/ignored/... when IKPddb is in "running" state.
* preparing IKPdb to be able to run in "client" (vs "server" mode today) so that it will be usable inside a deployed docker or lambda.

This work is done on an ikpdb (python2) branch 

Cyril

**Comment by cmorisse** [comment]
Implemented in version 1.2.1.
